// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeWNFoKRkyBOqZfwXIK8-jmDhRai_kFho',
    appId: '1:40749760771:web:0656d5196d88e187806936',
    messagingSenderId: '40749760771',
    projectId: 'fir-5ca9f',
    authDomain: 'fir-5ca9f.firebaseapp.com',
    storageBucket: 'fir-5ca9f.firebasestorage.app',
    measurementId: 'G-CHTXWHCV7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkpuogpAcDV6zx6wMVYqQbJQL3yU7yNe4',
    appId: '1:40749760771:android:9a95f161a836a96e806936',
    messagingSenderId: '40749760771',
    projectId: 'fir-5ca9f',
    storageBucket: 'fir-5ca9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJlA3hX8tLVmUzQJxirFQmwyZIc2jsUvU',
    appId: '1:40749760771:ios:d8da90811c8d3163806936',
    messagingSenderId: '40749760771',
    projectId: 'fir-5ca9f',
    storageBucket: 'fir-5ca9f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJlA3hX8tLVmUzQJxirFQmwyZIc2jsUvU',
    appId: '1:40749760771:ios:d8da90811c8d3163806936',
    messagingSenderId: '40749760771',
    projectId: 'fir-5ca9f',
    storageBucket: 'fir-5ca9f.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeWNFoKRkyBOqZfwXIK8-jmDhRai_kFho',
    appId: '1:40749760771:web:0d4c5ca5fa4f109d806936',
    messagingSenderId: '40749760771',
    projectId: 'fir-5ca9f',
    authDomain: 'fir-5ca9f.firebaseapp.com',
    storageBucket: 'fir-5ca9f.firebasestorage.app',
    measurementId: 'G-KQEQHCJJF6',
  );
}
